- name: Apache server instalado
  hosts: all
  become: yes
  tasks:
  - name: Instalar Git
    yum:
      name: git
      state: latest
  - name: Instalar Apache
    yum:
      name: httpd
      state: latest
  - name: Clone web index
    git:
      repo: https://github.com/cadyszy/website
      dest: /var/www/html/
  - name: Apache started e enable
    service:
      name: httpd
      enabled: true
      state: started
      
