- name: Apache server instalado
  hosts: all
  become: yes
  tasks:
  - name: Ultima versao do apache server instalado
    yum:
      name: httpd
      state: latest
- name: Apache started e enable
  service:
    name: httpd
    enabled: true
    state: started
