- name: Apache server instalado
  hosts: all
  become: yes
  tasks:
  - name: Instalar Git
    yum:
      name: git
      state: latest
  - name: Instalar Apache
    yum:
      name: httpd
      state: latest
  - name: Copiar index
    copy:
      src: /var/lib/awx/projects/_10__git/default.html
      dest: /var/www/html/index.html
  - name: Apache started e enable
    service:
      name: httpd
      enabled: true
      state: started
      
